### ISSUE TITLE
[Bug] WizardryUtils Summoned Item CapNBT prevents proper usage of AE2Stuff Adv. Inscribers

### ISSUE THREAD

**Issue by anabsolutesloth** [WinDanesz/WizardryUtils#10]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

Related Issue on AE2S Github: https://github.com/bdew-minecraft/ae2stuff/issues/193

Removing WizardryUtils allows for regular behaviour.
I suspect this is because of WizardryUtils Summoned Item CapNBT, which is applied to all items.
There are hack-ish fixes to this problem (such as through Crafttweaker), though closure on if this can be addressed from your end would be appreciated, it's likely that some other mods are impacted aswell.

### Expected behaviour

Item is allowed to go in central slot of Adv. Inscriber

### Steps to reproduce

1. Install AE2Stuff, WizardryUtils, and Dependencies
2. Enter a World
3. place AE2S Advanced Inscriber
4. attempt to insert Diamond, Gold, Pure Certus, or Redstone
5. item refuses to go into central slot

### Environment (Singleplayer/Server, etc.)

Issue present on both sides

### Mod version

1.1.1

### Forge version

1.12.2 - 14.23.5.2860

### Other mods

Applied Energistics 2 - rv6-stable-7
AE2 Stuff - 0.7.0.4-mc1.12.2
bdlib - 1.14.3.12-mc1.12.2
EBWizardry - 4.3.8

**Comment by WinDanesz** [comment]
Fixed by #23
