### ISSUE TITLE
Adding this mod will cause the furnace to only fire IC2 minerals one at a time before moving on to the next mineral until I take it out

### ISSUE THREAD

**Issue by haozaizai1** [WinDanesz/WizardryUtils#21]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

Adding this mod will cause the furnace to only fire IC2 minerals one at a time before moving on to the next mineral until I take it out

### Expected behaviour

Fix this bug

### Steps to reproduce

Adding this mod will cause the furnace to only fire IC2 minerals one at a time before moving on to the next mineral until I take it out

### Environment (Singleplayer/Server, etc.)

Singleplayer

### Mod version

1.1.4

### Forge version

1.12.2-14.23.5.2860

### Other mods

IC2 WizardryUtils

**Comment by WinDanesz** [comment]
fixed by e4604f2adc12ae7cd74dfeda9516327314a8cc21
