### ISSUE TITLE
WizardryUtils causes vanilla items to stop stacking when paired with FastFurnace

### ISSUE THREAD

**Issue by Awesominer100** [WinDanesz/WizardryUtils#22]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

I placed wood in a furnace and smelted it into charcoal, but the second charcoal didn't start smelting. I took out the first charcoal and the next charcoal started smelting.

### Expected behaviour

Charcoal should stack on itself in a furnace.

### Steps to reproduce

1. Create an instance with Wizardry Utils and FastFurnace
2. Try to put more than one wood block, cactus, raw meat, vanilla ore, etc., in a furnace (I tested with coal)
3. It doesn't work (but magic crystal ore does, for some reason...)

### Environment (Singleplayer/Server, etc.)

Singleplayer

### Mod version

1.1.4

### Forge version

1.12.2 - 14.23.5.2859

### Other mods

FastFurnace
Electroblob's Wizardry

**Comment by WinDanesz** [comment]
fixed by e4604f2adc12ae7cd74dfeda9516327314a8cc21
