### ISSUE TITLE
[Bug] Default lang file is wrong

### ISSUE THREAD

**Issue by RulerOfEternity** [WinDanesz/WizardryUtils#25]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

The attributes in the lang file need to be fixed and have the %% removed from them:

attribute.name.wizardryutils.SpellBlast=%% Spell Blast --> attribute.name.wizardryutils.SpellBlast=Spell Blast

Also:
1. You mentioned to me that you had to do some extra fixes in regards to the attributes or something, but I could be wrong.
2. There aren't any element specific potency options, only one for all elements, I'm not sure if that's a bug or if it's not a feature yet but I wanted to mention it.

### Expected behaviour

Should be "attribute.name.wizardryutils.SpellBlast=Spell Blast" (APPLIES TO ALL OF THE ATTRIBUTES!)

### Steps to reproduce

Just give yourself an item with any of the mod's added attributes.

### Environment (Singleplayer/Server, etc.)

Singleplayer

### Mod version

1.5.10

### Forge version

1.12.2 - 14.23.5.2860

### Other mods

![Screenshot 2023-11-25 211529](https://github.com/WinDanesz/WizardryUtils/assets/76789367/d221a9b6-5090-47cb-9c0d-96ce335c61f6)

**Comment by WinDanesz** [comment]
fixed by d41bba6731f89616ea2ef60cfe9f58428475e914
